name: Tests

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: ruby-${{ matrix.ruby }} ${{ matrix.gemfile }}
    strategy:
      matrix:
        ruby: ["2.7", "2.6"]
        gemfile:
          - rails_5
          - rails_6
          - rails_6_1
          - rails_master
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
      BUNDLE_PATH_RELATIVE_TO_CWD: true

    steps:
      - uses: actions/checkout@master

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: default
          bundler-cache: true

      - name: StandardRb check
        run: bundle exec standardrb

      - name: Run tests
        env:
          RAILS_ENV: test
        run: |
          bundle exec rake
