name: Tests

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: ruby-${{ matrix.ruby }} ${{ matrix.gemfile }}
    strategy:
      matrix:
        ruby: ['3.0', '3.1', '3.2', '3.3', head]
        gemfile:
          - rails_6_1
          - rails_7
          - rails_7_1
          - rails_main
          - sidekiq_6
          - sidekiq_7

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
      BUNDLE_PATH_RELATIVE_TO_CWD: true

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: default
          bundler-cache: true
          rubygems: latest
      - name: StandardRb check
        run: bundle exec standardrb
      - name: Run tests
        env:
          RAILS_ENV: test
        run: |
          bundle exec rake
