name: Tests

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["2.7", "2.6"]
        gemfile:
          - gemfiles/rails_5.gemfile
          - gemfiles/rails_6.gemfile
          - gemfiles/rails_6.1.gemfile
          - gemfiles/rails_master.gemfile

    steps:
      - uses: actions/checkout@master

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Install dependencies
        run: |
          sudo apt-get install libsqlite3-dev

      - name: StandardRb check
        run: bundle exec standardrb

      - name: Run tests
        env:
          RAILS_ENV: test
        run: |
          bundle exec rake
