name: Tests

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: ruby-${{ matrix.ruby }} ${{ matrix.gemfile }}
    strategy:
      matrix:
        ruby: [ '2.6', '2.7', '3.0', '3.1']
        gemfile:
          - rails_5
          - rails_6
          - rails_6_1
          - rails_7
          - rails_main
          - sidekiq_7
        exclude:
          - ruby: '3.1'
            gemfile: rails_5
          - ruby: '3.0'
            gemfile: rails_5
          # Rails 7 requires Ruby 2.7 or higher
          - ruby: '2.6'
            gemfile: rails_7
          - ruby: '2.6'
            gemfile: rails_main
          - ruby: '2.6'
            gemfile: sidekiq_7

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
      BUNDLE_PATH_RELATIVE_TO_CWD: true

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: default
          bundler-cache: true
      - name: StandardRb check
        run: bundle exec standardrb
      - name: Run tests
        env:
          RAILS_ENV: test
        run: |
          bundle exec rake
